"""Internal representation of a score, plus the suggestion and edit vocabulary.

This package is pure data: pydantic models, no XML, no Qt, no OpenCV. Everything else in the
system is written against these types, which is what keeps the parser, the detectors, the CV
stage and the UI independently testable.
"""

from .edit import (
    EditAction,
    EditOperation,
    InsertRestOp,
    RemoveElementOp,
    SetAccidentalOp,
    SetArticulationOp,
    SetClefOp,
    SetDurationOp,
    SetDynamicOp,
    SetKeyOp,
    SetPitchOp,
    SetSlurOp,
    SetTieOp,
    SetVoiceOp,
)
from .events import (
    NO_REF,
    Barline,
    BarlineLocation,
    Chord,
    Direction,
    DirectionKind,
    Duration,
    ElementRef,
    Event,
    Lyric,
    Note,
    RepeatDirection,
    Rest,
    Spanner,
    SpannerRole,
    StemDirection,
    TieState,
    TimeModification,
)
from .geometry import BoundingBox, SourceRegion, StaffMetrics
from .pitch import ACCIDENTAL_ALTER, ALTER_ACCIDENTAL, Accidental, Pitch, Step
from .rational import ONE, ZERO, Rational, to_rational
from .score import (
    FLAT_ORDER,
    SHARP_ORDER,
    AttributeChange,
    Clef,
    ClefSign,
    KeySignature,
    Measure,
    MeasureAttributes,
    Mode,
    ParseIssue,
    Part,
    PartGroup,
    Score,
    ScoreMetadata,
    TimeSignature,
    Transpose,
)
from .suggestion import (
    AnalysisReport,
    Channel,
    ConfidenceBreakdown,
    Evidence,
    Severity,
    Suggestion,
    SuggestionKind,
    SuggestionStatus,
    SuggestionTarget,
)

__all__ = [
    "ACCIDENTAL_ALTER",
    "ALTER_ACCIDENTAL",
    "FLAT_ORDER",
    "NO_REF",
    "ONE",
    "SHARP_ORDER",
    "ZERO",
    "Accidental",
    "AnalysisReport",
    "AttributeChange",
    "Barline",
    "BarlineLocation",
    "BoundingBox",
    "Channel",
    "Chord",
    "Clef",
    "ClefSign",
    "ConfidenceBreakdown",
    "Direction",
    "DirectionKind",
    "Duration",
    "EditAction",
    "EditOperation",
    "ElementRef",
    "Event",
    "Evidence",
    "InsertRestOp",
    "KeySignature",
    "Lyric",
    "Measure",
    "MeasureAttributes",
    "Mode",
    "Note",
    "ParseIssue",
    "Part",
    "PartGroup",
    "Pitch",
    "Rational",
    "RemoveElementOp",
    "RepeatDirection",
    "Rest",
    "Score",
    "ScoreMetadata",
    "SetAccidentalOp",
    "SetArticulationOp",
    "SetClefOp",
    "SetDurationOp",
    "SetDynamicOp",
    "SetKeyOp",
    "SetPitchOp",
    "SetSlurOp",
    "SetTieOp",
    "SetVoiceOp",
    "Severity",
    "SourceRegion",
    "Spanner",
    "SpannerRole",
    "StaffMetrics",
    "StemDirection",
    "Step",
    "Suggestion",
    "SuggestionKind",
    "SuggestionStatus",
    "SuggestionTarget",
    "TieState",
    "TimeModification",
    "TimeSignature",
    "Transpose",
    "to_rational",
]
